version: '3'
services:
    api:
    build: ./api/
    container_name: backend
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      DB_USER: 'postgres'
      DB_PASSWORD: 'example'
      DB_PORT: '3307'
      DB_NAME: 'example'
      CORS_PORT: '8080'
      CORS_ORIGIN: host.docker.internal
      API_PORT: '8081'

  